### ISSUE TITLE
Firefox base map rendering issue

### ISSUE THREAD

**Issue by jtloong** [rdrnt/tps-calls#1]
Love the project! 

I'm using Firefox on an Ubuntu machine and the base map wouldn't render. The points were there but the base map wasn't. When I opened it on Chrome it worked fine. Just wanted to let you know there's an issue there.

**Comment by rdrnt** [comment]
Hi! Thank you so much for the kind words.

I see on my end there was an error. I do plan on releasing v1.4 soon which improves the UI and map functionality. Though that won't be for another 1-2 weeks as I'm busy.

I'll be sure to reach out if I need you to test something or it's fixed. Thanks again!
