### ISSUE TITLE
error An unexpected error occurred: "https://npm.pkg.github.com/download/@rdrnt/tps-calls-shared/0.1.4/5f4c3f273ddf9e7213a46c062a5f8be849d2d24b8e0c520c4ff29f90b29cbc13: Request failed                                                      

### ISSUE THREAD

**Issue by sd17** [rdrnt/tps-calls#8]
I am not very familiar with React, but during yarn add typescript i'm getting the error: error An unexpected error occurred: "https://npm.pkg.github.com/download/@rdrnt/tps-calls-shared/0.1.4/5f4c3f273ddf9e7213a46c062a5f8be849d2d24b8e0c520c4ff29f90b29cbc13: Request failed                                                      

Would you mind helping?

**Comment by rdrnt** [comment]
Hey there,

This is because you don't have access to the tps-calls-shared npm package. Send me an email and I can give you the correct access. 

Thanks!
